"""Initial schema

Revision ID: d055faabf439
Revises: 
Create Date: 2022-10-25 21:59:00.036320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd055faabf439'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_closed', sa.Boolean(), nullable=False),
    sa.Column('allow_no_cert', sa.Boolean(), nullable=False),
    sa.Column('system_title', sa.Boolean(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('application_version', sa.Integer(), nullable=False),
    sa.Column('online_play_policy', sa.Enum('MEMBERSHIP_REQUIRED', 'FREE'), nullable=False),
    sa.Column('policy_handler', sa.Enum('SYSTEM', 'GAME_SERVER'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('ban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rom_id', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ban')
    op.drop_table('application')
    # ### end Alembic commands ###
